# render.yaml
services:
  - type: web
    name: careerpulse
    runtime: node
    plan: free
    buildCommand: chmod +x ./render-build.sh ./check-deployment.sh ./render-diagnose.sh && ./render-build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: careerpulse-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "true"

databases:
  - name: careerpulse-db
    plan: free
    ipAllowList: []
